### How to import pandas and check the version?

In [1]:
import pandas as pd
print(pd.__version__)
pd.show_versions(as_json=True)

0.25.1
{'system': {'commit': None, 'python': '3.7.4.final.0', 'python-bits': 64, 'OS': 'Darwin', 'OS-release': '19.3.0', 'machine': 'x86_64', 'processor': 'i386', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'en_US.UTF-8', 'LOCALE': 'en_US.UTF-8'}, 'dependencies': {'pandas': '0.25.1', 'numpy': '1.17.2', 'pytz': '2019.3', 'dateutil': '2.8.0', 'pip': '20.0.2', 'setuptools': '41.2.0', 'Cython': '0.29.13', 'pytest': '5.2.1', 'hypothesis': None, 'sphinx': '2.2.0', 'blosc': None, 'feather': None, 'xlsxwriter': '1.2.1', 'lxml.etree': '4.4.1', 'html5lib': '1.0.1', 'pymysql': '0.9.3', 'psycopg2': None, 'jinja2': '2.10.3', 'IPython': '7.8.0', 'pandas_datareader': None, 'bs4': '4.8.0', 'bottleneck': '1.2.1', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.1.1', 'numexpr': '2.7.0', 'odfpy': None, 'openpyxl': '3.0.0', 'pandas_gbq': None, 'pyarrow': None, 'pytables': None, 's3fs': None, 'scipy': '1.3.1', 'sqlalchemy': '1.3.9', 'tables': '3.5.2', 'xarray': None, 'xlrd': '1.2.0', 'xlwt': '1.3

### How to create a series from a list, numpy array and dict?

In [22]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [23]:

dictionary=dict(zip(ser1,ser2))


### How to convert the index of a series into a column of a dataframe?

In [42]:
# Input
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Solution
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


### How to combine many series to form a dataframe?

In [25]:
#1
df=pd.DataFrame(ser1,ser2)

#2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
#3
df=pd.concat([ser1,ser2],axis=1)

### How to combine many series to form a dataframe?

### How to assign name to the series’ index?

In [27]:
ser.name='alphabets'
ser.head()

a    0
b    1
c    2
d    3
e    4
Name: alphabets, dtype: int64

### How to get the items of series A not present in series B?

In [30]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])


In [34]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

### How to get the items not common to both series A and series B?

In [41]:

union=pd.Series(np.union1d(ser1,ser2))
intersect=pd.Series(np.intersect1d(ser1,ser2))
union[~union.isin(intersect)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

### How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [55]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser[:5]

0    e
1    a
2    d
3    c
4    c
dtype: object

### How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [44]:
# input
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [53]:
ser.value_counts()

3    4
4    3
1    3
2    2
dtype: int64

### How to bin a numeric series to 10 groups of equal size?

In [56]:
ser = pd.Series(np.random.random(20))

In [58]:
#pd.cut(ser,bins=10,labels=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"])

0      1st
1     10th
2      9th
3      5th
4      8th
5     10th
6      7th
7      6th
8      8th
9      9th
10     6th
11     5th
12     2nd
13     2nd
14     3rd
15     7th
16     1st
17     6th
18     1st
19     7th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [59]:
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0     2nd
1    10th
2     9th
3     4th
4     8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

### How to convert a numpy array to a dataframe of given shape? (L1)
Reshape the series ser into a dataframe with 7 rows and 5 columns

In [60]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [64]:
pd.DataFrame(ser.values.reshape(7,5))

0  1  2  3  4
0  4  9  1  3  9
1  1  4  3  4  7
2  2  6  8  7  9
3  9  2  2  5  4
4  2  5  1  1  5
5  8  6  7  4  4
6  1  6  7  6  3

### How to find the positions of numbers that are multiples of 3 from a series?

In [65]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [70]:
ser[ser %3==0]
#np.argwhere(ser%3==0)

3    9
dtype: int64

### How to extract items at given positions from a series
From ser, extract the items at positions in list pos.

In [71]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

###  How to stack two series vertically and horizontally ?

In [72]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [74]:
# vertical
df1=pd.concat([ser1,ser2])
df1.head()

0    0
1    1
2    2
3    3
4    4
dtype: object

In [77]:
# Horizontal
new_ser=ser1.append(ser2)
new_ser

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

### How to get the positions of items of series A in another series B?

### How to compute the mean squared error on a truth and predicted series?

In [78]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [83]:
np.mean((pred-truth)**2)

0.27085047679464247

### How to convert the first character of each element in a series to uppercase?

### How to calculate the number of characters in each word in a series?
Difference of differences between the consequtive numbers of ser.

In [104]:
ser = pd.Series(['how', 'to', 'win'])

In [107]:
ser.apply(lambda x: len(x))

0    3
1    2
2    3
dtype: int64

### How to compute difference of differences between consequtive numbers of a series?

In [109]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [113]:
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


### How to convert a series of date-strings to a timeseries?

In [98]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [99]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

### How to get the day of month, week number, day of year and day of week from a series of date
Get the day of month, week number, day of year and day of week from ser.

In [86]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [96]:
from dateutil.parser import parse
ser_ts= ser.map(lambda x:parse(x))

In [97]:
# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Date: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Date: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.weekday_name.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Date:  [53, 5, 9, 14, 19, 23]
Date:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


### How to convert year-month string to dates corresponding to the 4th day of the month?

In [115]:
import pandas as pd
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))

# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

### How to filter words that contain atleast 2 vowels from a series?


In [116]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [ ]:
def find_two_vowels(item):
    

### How to filter valid emails from a series?

In [117]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

In [122]:
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'



### How to get the mean of a series grouped by another series?

In [121]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

print(weights.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'banana', 'banana', 'carrot', 'carrot', 'apple', 'carrot', 'carrot', 'apple']


### How to compute the euclidean distance between two series?

In [123]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [130]:
#np.sqrt(sum((p-q)**2))

np.linalg.norm(p-q)

18.16590212458495

### How to find all the local maxima (or peaks) in a numeric series?
Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

In [128]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

### How to replace missing spaces in a string with the least frequent character?
Replace the spaces in my_str with the least frequent character.

### How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

### How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.

In [131]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [132]:
ser.isna

<bound method Series.isna of 2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64>

### How to compute the autocorrelations of a numeric series?m

In [134]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [137]:
ser[:10]

0     4.186222
1     6.829676
2    12.172024
3    -0.674903
4     4.576663
5    -5.115250
6    -4.895833
7    19.685320
8    18.177658
9    -0.083624
dtype: float64

### How to import only every nth row from a csv file to create a dataframe?

In [138]:
# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

### How to create a dataframe with rows as strides from a given series?

In [139]:
L = pd.Series(range(15))

### How to import only specified columns from a csv file?
read only crim and medv columns

In [144]:
df=pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv",usecols=['crim','medv'])
df.head()

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

### How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [145]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [146]:
#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
print(df.get_dtype_counts())


# summary sttistics
df_stats=df.describe()

# numpy array 
df_arr = df.values

# list
df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  


[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,


###  How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [234]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.shape)
print(df.dtypes)

print(df.describe())

# numpy array
df.values

# to list
df_list =df.values.tolist()

(93, 27)
Manufacturer       object
Model              object
Type               object
Min.Price         float64
Price             float64
                   ...   
Rear.seat.room    float64
Luggage.room      float64
Weight            float64
Origin             object
Make               object
Length: 27, dtype: object
       Min.Price      Price  Max.Price   MPG.city  MPG.highway  ...  \
count  86.000000  91.000000  88.000000  84.000000    91.000000  ...   
mean   17.118605  19.616484  21.459091  22.404762    29.065934  ...   
std     8.828290   9.724280  10.696563   5.841520     5.370293  ...   
min     6.700000   7.400000   7.900000  15.000000    20.000000  ...   
25%    10.825000  12.350000  14.575000  18.000000    26.000000  ...   
50%    14.600000  17.700000  19.150000  21.000000    28.000000  ...   
75%    20.250000  23.500000  24.825000  25.000000    31.000000  ...   
max    45.400000  61.900000  80.000000  46.000000    50.000000  ...   

           Width  Turn.circle  Rear.sea

### How to extract the row and column number of a particular cell with given criterion?
Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

In [151]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.dtypes[:5]

Manufacturer     object
Model            object
Type             object
Min.Price       float64
Price           float64
dtype: object

In [239]:
# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

# Get the value
print(df.iat[row[0], col[0]])
print(df.iloc[row[0], col[0]])

# Alternates
df.at[row[0], 'Price']
df.get_value(row[0], 'Price')

print(row,col)

61.9
61.9
[58] [4]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  


### How to rename a specific columns in a dataframe?
Rename the column Type as CarType in df and replace the ‘.’ in column names with ‘_’.

In [240]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [243]:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


### How to check if a dataframe has any missing values?

In [244]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [245]:
sum(df.isna().sum())>0

True

In [246]:
df.isnull().values.any()

True

### How to count the number of missing values in each column?

In [247]:
n_missings_each_col = df.apply(lambda x: x.isnull().sum())

In [248]:
n_missings_each_col

Manufacturer       4
Model              1
Type               3
Min.Price          7
Price              2
                  ..
Rear.seat.room     4
Luggage.room      19
Weight             7
Origin             5
Make               3
Length: 27, dtype: int64

### How to replace missing values of multiple numeric columns with the mean?

In [257]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [260]:

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


### How to use apply function on existing columns with global variables as additional arguments?

### How to select a specific column from a dataframe as a dataframe instead of a series

In [329]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [330]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

# Alternately the following returns a Series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])

pandas.core.series.Series

### How to change the order of columns of a dataframe?

In [318]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [319]:
# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    if(isinstance(col1,str) & isinstance(col2,str)):
        i1, i2 = colnames.index(col1), colnames.index(col2)
        colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
        return df[colnames]
    
    if(isinstance(col1,int) & isinstance(col2,int)):
        a,b=df.iloc[:,col1].copy(), df.iloc[:,col2].copy()
        df.iloc[:, col1], df.iloc[:,col2] = b, a
        return df

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

### How to set the number of rows and columns displayed in the output?

In [321]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [322]:
# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

### How to format or suppress scientific notations in a pandas dataframe?
Suppress scientific notations like ‘e-03’ in df and print upto 4 numbers after decimal.

In [262]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df

random
0  2.823975e-02
1  9.724486e-04
2  3.396688e-18
3  5.419031e-03

In [263]:
# option 1
df.round(4)

# option 2
df.apply(lambda x: '%.4f' % x, axis=1)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0282
1  0.0010
2  0.0000
3  0.0054


### How to format all the values in a dataframe as percentages?
Format the values in column 'random' of df as percentages.

In [335]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df

random
0  0.373457
1  0.630884
2  0.863410
3  0.845823

In [342]:
# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})
out

### How to filter every nth row in a dataframe?

In [346]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [349]:
# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


### How to create a primary key index by combining relevant columns?

In [350]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

### How to get the row number of the nth largest value in a column?

In [359]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
n=5

In [370]:
df['a'].nlargest(n).index[-1]

7

In [365]:
df['a'].argsort()[::-1][n]

7

### How to find the position of the nth largest value greater than a given value?

In [374]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [380]:
# Solution
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
np.argwhere(ser > ser.mean())[1]

ser:  [78, 48, 55, 80, 23, 43, 27, 51, 82, 96, 7, 80, 31, 99, 90] mean:  59


/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:61: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return bound(*args, **kwds)


array([3])

### How to get the last n rows of a dataframe with row sum > 100?

In [381]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

### How to find and cap outliers from a series or dataframe column?

In [382]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [385]:
# >Q3+IQR*3   | < Q1-IQR*3
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

In [384]:
capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


### How to reshape a dataframe to the largest possible square after removing the negative values?
Reshape df to the largest possible square with negative values removed. Drop the smallest values if need be. The order of the positive numbers in the result should remain the same as the original.

In [351]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [352]:
# 1. remove negative
# 2. find # of valid numbers & maximum square 
arr=df[df>0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

In [353]:
# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[33.  5. 30. 46. 28. 48. 38. 26.]
 [32. 21. 19. 10. 26. 34. 24.  5.]
 [48.  5. 17. 26. 37.  6.  4. 30.]
 [28. 43. 24. 19. 12. 24. 10. 12.]
 [11. 41. 25.  4.  6. 36. 21. 17.]
 [ 7. 49. 30. 29.  7. 20. 43. 27.]
 [18. 36. 17. 22. 33. 19. 20. 23.]
 [12. 41. 30. 31. 45. 14. 39.  6.]]


### How to swap two rows of a dataframe?

In [298]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [299]:
def swap(df,i1,i2):
    a,b=df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return(df)

In [300]:
swap(df,0,1)

0   1   2   3   4
0   5   6   7   8   9
1   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

### How to reverse the rows of a dataframe?

In [192]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [ ]:
df

### How to create one-hot encodings of a categorical variable (dummy variables)?

In [208]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

In [194]:
# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


###  Which column contains the highest number of row-wise maximum values?

In [2]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

In [3]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  1


/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:61: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return bound(*args, **kwds)


### How to create a new column that contains the row number of nearest column by euclidean distance?

In [4]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

In [6]:
# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

### How to know the maximum possible correlation value of each column against other columns?

In [7]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

In [9]:
# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.94 0.61 0.77 0.64 0.94 0.64 0.65 0.81 0.65 0.81]


### How to create a column containing the minimum by maximum of each row?

In [10]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [11]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)

### How to create a column that contains the penultimate value in each row?
Create a new column 'penultimate' which has the second largest value of each row of df.

In [23]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [20]:
# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9  penultimate
0  32  79  28  76  66  46  98  77  39  80           80
1  72  21  29  14  47  81  32  34  79  24           79
2  81  11  65  78  21  14  44  48  70  47           78
3  79  35  92   2   2  71  99  66  59  83           92
4  44  29  74  53   8  33  92  91  88  50           91
5  51  31  48  49  52  43  54   2  68  52           54
6  81  18  55  95  83  92  70  10  21  20           92
7  61  89  55  73  60  56  62  50  52  35           73


### How to normalize all columns in a dataframe?
Normalize all columns of df by subtracting the column mean and divide by standard deviation. <br>
Range all columns of df such that the minimum value in each column is 0 and max is 1.

In [37]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [38]:
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))

In [40]:
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))

### How to compute the correlation of each row with the suceeding row?

In [42]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [43]:
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[0.22, 0.36, 0.24, 0.3, 0.15, -0.02, 0.05]

### How to replace both the diagonals of dataframe with 0?

In [58]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
# pd.series.reshape

In [66]:
for i in range(df.shape[0]):
    for j in range(df.shape[1]):
        if i==j:
            df.iloc[i,j]=0

There are three primary indexers for pandas. We have the indexing operator itself (the brackets []), .loc, and .iloc. Let's summarize them: <br>

* [] - Primarily selects subsets of columns, but can select rows as well. Cannot simultaneously select rows and columns. <br>
* .loc - selects subsets of rows and columns by label only <br>
* .iloc - selects subsets of rows and columns by integer location only <br>
I almost never use .at or .iat as they add no additional functionality and with just a small performance increase. I would discourage their use unless you have a very time-sensitive application. Regardless, we have their summary: <br>

* .at selects a single scalar value in the DataFrame by label only <br>
* .iat selects a single scalar value in the DataFrame by integer location only <br>
In addition to selection by label and integer location, boolean selection also known as boolean indexing exists. <br>



In [67]:
# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

### How to get the particular group of a groupby dataframe by key?

In [82]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

In [84]:
for k,v in df_grouped:
    if k=='apple':
        print(v)

    col1      col2  col3
0  apple  0.849714    13
3  apple  0.375828    10
6  apple  0.537782     0


In [85]:
df_grouped.get_group('apple')

col1      col2  col3
0  apple  0.849714    13
3  apple  0.375828    10
6  apple  0.537782     0

### How to get the n’th largest value of a column when grouped by another column?

In [86]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [ ]:



# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

### How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?

In [221]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

### How to join two dataframes by 2 columns so they have only the common rows?

In [223]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

### How to get the positions where values of two columns match?

In [87]:
# Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1==df.fruit2)

(array([6, 7, 8, 9]),)

### How to create lags and leads of a column in a dataframe?

### How to create lags and leads of a column in a dataframe?
Create two new columns in df, one of which is a lag1 (shift column a down by 1 row) of column ‘a’ and the other is a lead1 (shift column b up by 1 row).

In [88]:
# Input
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

In [92]:
df['a_lead']=df.a.shift(1)
df['a_lag']=df.a.shift(-1)

### How to get the frequency of unique values in the entire dataframe?
Get the frequency of unique values in the entire dataframe df.

In [93]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

In [94]:
# Input
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

8    6
6    4
9    3
7    2
5    1
4    1
3    1
2    1
1    1
dtype: int64

### How to split a text column into two separate columns?

In [95]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

In [96]:
print(df)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka
